class UserExistsError(Exception):
    pass


class UserDoesNotExistError(Exception):
    pass
